spring.application.name=app-ahorrito
debug=false

# Configuración de H2 en modo archivo
spring.datasource.url=jdbc:postgresql://localhost:5432/ahorrito
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_LOCAL_PASSWORD:proyectox!}

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Seguridad y Semilla de Datos
app.security.seed-admin=true
app.security.registration-enabled=true
app.security.max-users=100

# Compression GZIP
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
server.compression.min-response-size=1024

