CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE codigos_recuperacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_hash VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL UNIQUE,
    creado_en TIMESTAMP NOT NULL,
    CONSTRAINT fk_codigos_recuperacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE perfiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    rango VARCHAR(100),
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_perfiles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    color VARCHAR(20),
    limite_gasto NUMERIC(19,2),
    version INTEGER,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_categorias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT uq_categorias_nombre_usuario UNIQUE (nombre, usuario_id)
);

CREATE TABLE carteras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    monto_objetivo NUMERIC(19,2),
    monto_actual NUMERIC(19,2) NOT NULL,
    descripcion VARCHAR(255),
    es_objetivo_ahorro BOOLEAN NOT NULL,
    color VARCHAR(20),
    orden INTEGER,
    version INTEGER,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_carteras_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    fecha DATE NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    categoria_id BIGINT,
    cartera_id BIGINT,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_transacciones_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE SET NULL,
    CONSTRAINT fk_transacciones_cartera FOREIGN KEY (cartera_id) REFERENCES carteras(id) ON DELETE SET NULL,
    CONSTRAINT fk_transacciones_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE eventos_calendario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    fecha DATE NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_eventos_calendario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Explicit indexes on foreign key columns
CREATE INDEX idx_transacciones_usuario_id ON transacciones(usuario_id);
CREATE INDEX idx_transacciones_categoria_id ON transacciones(categoria_id);
CREATE INDEX idx_transacciones_cartera_id ON transacciones(cartera_id);

CREATE INDEX idx_carteras_usuario_id ON carteras(usuario_id);

CREATE INDEX idx_categorias_usuario_id ON categorias(usuario_id);

CREATE INDEX idx_eventos_calendario_usuario_id ON eventos_calendario(usuario_id);
