CREATE TABLE gastos_fijos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    dia_pago INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    categoria_id BIGINT,
    cartera_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_gastos_fijos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE SET NULL,
    CONSTRAINT fk_gastos_fijos_cartera FOREIGN KEY (cartera_id) REFERENCES carteras(id) ON DELETE CASCADE,
    CONSTRAINT fk_gastos_fijos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT chk_dia_pago CHECK (dia_pago >= 1 AND dia_pago <= 31),
    CONSTRAINT chk_monto_positivo CHECK (monto > 0)
);

CREATE INDEX idx_gastos_fijos_usuario_id ON gastos_fijos(usuario_id);
CREATE INDEX idx_gastos_fijos_categoria_id ON gastos_fijos(categoria_id);
CREATE INDEX idx_gastos_fijos_cartera_id ON gastos_fijos(cartera_id);
