ALTER TABLE gastos_fijos ADD COLUMN permanente BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE gastos_fijos ADD COLUMN tipo_cambio VARCHAR(20) NOT NULL DEFAULT 'tarjeta';
ALTER TABLE gastos_fijos ADD COLUMN cotizacion_manual NUMERIC(19,2) DEFAULT NULL;
ALTER TABLE gastos_fijos ADD COLUMN fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE;
