CREATE TABLE gasto_checklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    fecha DATE NOT NULL,
    descripcion VARCHAR(255),
    permanente BOOLEAN NOT NULL DEFAULT FALSE,
    completado BOOLEAN NOT NULL DEFAULT FALSE,
    usuario_id BIGINT NOT NULL,
    cartera_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    transaccion_id BIGINT,
    CONSTRAINT fk_gasto_checklist_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_gasto_checklist_cartera FOREIGN KEY (cartera_id) REFERENCES carteras(id) ON DELETE CASCADE,
    CONSTRAINT fk_gasto_checklist_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE,
    CONSTRAINT fk_gasto_checklist_transaccion FOREIGN KEY (transaccion_id) REFERENCES transacciones(id) ON DELETE SET NULL,
    CONSTRAINT chk_monto_gasto_checklist CHECK (monto > 0)
);

CREATE INDEX idx_gasto_checklist_usuario_fecha ON gasto_checklist(usuario_id, fecha);
CREATE INDEX idx_gasto_checklist_cartera_id ON gasto_checklist(cartera_id);
CREATE INDEX idx_gasto_checklist_categoria_id ON gasto_checklist(categoria_id);
CREATE INDEX idx_gasto_checklist_transaccion_id ON gasto_checklist(transaccion_id);
